const mongoose = require("mongoose");

const buyerContractSchema = new mongoose.Schema({
  buyerContractStatus: String,
  buyerContractId: String,
  buyername: String,
  buyerId: String,
  phone: String,
  email: String,
  addressLine1: String,
  addressLine2: String,
  addressLine3: String,
  city: String,
  state: String,
  country: String,
  postcode: String,
  bankDetails: String,
  fssai: String,
  iecNo: String,
  panNo: String,
  gstNo: String,
  eximCode: String,
  pan: String,
  brokerName: String,
  portOfDisemberkation: String,
  productSelection: String,
  product: String,
  defectivePercentage: String,
  productGradingGTA: String,
  specificationAndValue: String,
  origin: String,
  quoteDate: String,
  buyDate: String,
  buyRate: Number,
  buyQuantityMetricTonnes: Number,
  buyQuantityContainers: Number,
  allocatedContainers: Number,
  balanceContainers: Number,
  totalBuyAmount: Number,
  calculateTotalSellPriceAndBalanceContainers: String,
  monthOfShipment: String,
  buyerPurchaseOrderNumber: String,
  paymentTerms: String,
  breakup: String,
  packing: String,
  bagType: String,
  bagBranding: String,
  notes: String,
  contractTerms: String,
  proformaInvoiceSplitQuantityMetricTonnes: Number,
  generateProformaInvoiceEvenSplit: String,
  updateCustomInvoiceNumber: String,
  proformaInvoices: String,
  generateProformaInvoiceCustom: String,
  generateBuyerContract: String,
  buyerContractLink: String,
}, { timestamps: true });

module.exports = mongoose.model("BuyerContract", buyerContractSchema);
